import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from '@/components/Header'
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes'
import { Toaster } from "sonner";
import RedirectToDashboard from "@/components/redirectsToDashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JobSensei - Ai career coach",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: Readonly<RootLayoutProps>) {
  return (
    <ClerkProvider 
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <RedirectToDashboard />
            {children}
            <Toaster richColors />
            {/* <Footer/> */}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}